version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_CONNECTOR_URL=${VITE_CONNECTOR_URL}
      - VITE_GRAFANA_URL=${VITE_GRAFANA_URL}
      - VITE_GRAFANA_DASHBOARD_AUTH_TIMES=${VITE_GRAFANA_DASHBOARD_AUTH_TIMES}
      - VITE_GRAFANA_DASHBOARD_ADMIN_DASH_STATS=${VITE_GRAFANA_DASHBOARD_ADMIN_DASH_STATS}
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
