services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_CONNECTOR_URL=${VITE_CONNECTOR_URL}
      - VITE_GRAFANA_URL=${VITE_GRAFANA_URL}
      - VITE_GRAFANA_DASHBOARD_AUTH_TIMES=${VITE_GRAFANA_DASHBOARD_AUTH_TIMES}
      - VITE_GRAFANA_DASHBOARD_ADMIN_DASH_STATS=${VITE_GRAFANA_DASHBOARD_ADMIN_DASH_STATS}
      - VITE_BLOCKCHAIN_CHAIN_ID=${VITE_BLOCKCHAIN_CHAIN_ID}
      - VITE_BLOCKCHAIN_RPC_PROVIDER=${VITE_BLOCKCHAIN_RPC_PROVIDER}
      - VITE_BLOCKCHAIN_DID_REGISTRY_ADDR=${VITE_BLOCKCHAIN_DID_REGISTRY_ADDR}
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - frontend-network
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge