version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_CONNECTOR_URL=${CONNNECTOR_URL}
      - VITE_GRAFANA_URL=${GRAFANA_URL}
    ports:
      - "80:80"
    restart: unless-stopped
